from __future__ import annotations

import numpy as np
from scipy.optimize import minimize
from typing import Any, Optional, Union

try:
    import torch
except Exception:  # Make torch optional
    torch = None
import warnings

from sklearn.linear_model import LogisticRegression
import networkx as nx

import statsmodels.api as sm
import statsmodels.formula.api as smf

from .degrees_counts import degree_vertex, get_sum_degrees
from .lg_features import FeatureMode, build_pair_dataset, pair_feature_layer2

max_val = np.nan
eps = 1e-5

class NegativeLogLikelihoodLoss(torch.nn.Module if torch is not None else object):
    """DEPRECATED: paper-raw (alpha*S_i + beta*S_j + sigma) loss without
    Layer-2 conditioning. Kept only for reproducing the original notebook
    experiments. New code should use :class:`LogitRegEstimator` which is
    Layer-2 aware and exposes :meth:`compute_aic` / :meth:`select_d`.
    """

    def __init__(self, graph: np.ndarray, d: int) -> None:
        super(NegativeLogLikelihoodLoss, self).__init__()
        warnings.warn(
            "NegativeLogLikelihoodLoss is deprecated; use LogitRegEstimator "
            "(Layer-2 offset logit) for consistent results.",
            DeprecationWarning,
            stacklevel=2,
        )
        if torch is None:
            raise ImportError("PyTorch is required for NegativeLogLikelihoodLoss. Install with `pip install torch`.\n"
                              "Alternatively, use LogitRegEstimator which does not require torch.")
        self.graph = torch.tensor(graph, dtype=torch.float32)  # Ensure graph is a PyTorch tensor
        self.n = graph.shape[0]
        self.d = d

    def logistic_probability(self, sum_degrees: Any) -> Any:
        num = torch.exp(sum_degrees)
        denom = 1 + 1 * torch.exp(sum_degrees)
        return num / denom

    def forward(self, params: list) -> Any:
        alpha, beta, sigma = params
        likelihood = 0.0

        # Iterate over all possible edges
        for i in range(self.n):
            for j in range(i, self.n):
                degrees_i = get_sum_degrees(self.graph, i, self.d)
                degrees_j = get_sum_degrees(self.graph, j, self.d)
                sum_degrees_raw = ( alpha * degrees_i + beta * degrees_j )
                sum_degrees = ( sum_degrees_raw + sigma )

                p_ij = self.logistic_probability(sum_degrees)

                if self.graph[i, j] == 1:
                    likelihood += torch.log(p_ij + eps)  # Adding a small constant to avoid log(0)
                else:
                    likelihood += torch.log(1 - p_ij + eps)


        return -likelihood  # Return negative likelihood

class MLEGraphModelEstimator:
    """DEPRECATED: paper-raw MLE without Layer-2 conditioning.

    This estimator uses the original ``alpha * S_i + beta * S_j + sigma``
    formulation with no edge-removal correction, which is biased when the
    underlying graph was generated by the Layer-2 Gibbs sampler. New code
    should use :class:`LogitRegEstimator` instead.
    """

    def __init__(self, graph: np.ndarray, d: int) -> None:
        warnings.warn(
            "MLEGraphModelEstimator is deprecated; use LogitRegEstimator "
            "(Layer-2 offset logit) for consistent results.",
            DeprecationWarning,
            stacklevel=2,
        )
        if torch is None:
            raise ImportError(
                "PyTorch is required for MLEGraphModelEstimator. "
                "Install with `pip install torch`.\n"
                "Alternatively, use LogitRegEstimator which does not require torch.")
        self.graph = graph  # The observed adjacency matrix
        self.n = graph.shape[0]  # Number of nodes in the graph
        self.d = d  # Neighbourhood depth for degree features
        self.params_history = []  # History of parameters during optimization

    def logistic_probability(self, sum_degrees: Any) -> Any:
        num = torch.exp(sum_degrees)
        denom = 1 + torch.exp(sum_degrees)
        return num / denom

    def likelihood_function(self, params: list) -> float:
        """Negative log-likelihood function to be minimized."""
        alpha, beta, sigma = params
        likelihood = 0

        for i in range(self.n):
            for j in range(i, self.n):
                degrees_i = get_sum_degrees(self.graph, i, self.d)
                degrees_j = get_sum_degrees(self.graph, j, self.d)
                sum_degrees_raw = alpha * degrees_i + beta * degrees_j
                sum_degrees = sum_degrees_raw + sigma
                p_ij = self.logistic_probability(sum_degrees)

                if 1 - p_ij + eps <= 0:
                    return float(max_val)

                if self.graph[i, j] == 1:
                    try:
                        likelihood += np.log(abs(p_ij + eps))
                    except Exception:
                        return float(max_val)
                else:
                    try:
                        likelihood += np.log(abs(1 - p_ij + eps))
                    except Exception:
                        return float(max_val)

        return likelihood

    def estimate_parameters(
        self,
        initial_guess: Optional[list[float]] = None,
        learning_rate: float = 0.01,
        max_iter: int = 1000,
    ) -> tuple[float, float, float]:
        if initial_guess is None:
            initial_guess = [0.5, 0.1, 0.1]
        alpha, beta, sigma = [
            torch.tensor(x, dtype=torch.float32, requires_grad=True)
            for x in initial_guess
        ]
        optimizer = torch.optim.SGD([alpha, beta, sigma], lr=learning_rate)

        loss_function = NegativeLogLikelihoodLoss(self.graph, self.d)
        for _ in range(max_iter):
            optimizer.zero_grad()
            loss = loss_function([alpha, beta, sigma])
            loss.backward()
            optimizer.step()

            self.params_history.append([alpha.item(), beta.item(), sigma.item()])

        return alpha.item(), beta.item(), sigma.item()



# Main estimator for the LG graph
class LogitRegEstimator:
    def __init__(
        self,
        graph: Union[np.ndarray, nx.Graph],
        d: int,
        verbose: bool = False,
        layer2: bool = True,
        feature_mode: FeatureMode = "incremental",
    ) -> None:
        # NOTE: ``feature_mode`` defaults to ``"incremental"`` to match the
        # generator's default and the paper's offset-logit formulation. The
        # legacy ``"bounded"`` mode adds a nonzero pair term even at d=0,
        # which biases sigma_hat away from logit(empirical_density).
        self.graph = graph  # The observed adjacency matrix
        if isinstance(graph, np.ndarray):
            self.n = graph.shape[0]  # Number of nodes in the graph
            self.adj = graph
        elif isinstance(graph, nx.Graph):
            self.n = graph.number_of_nodes()
            self.adj = nx.to_numpy_array(graph)
        else:
            raise ValueError("Unsupported graph type. Please provide a NumPy array or NetworkX graph.")
        self.d = d # number of degrees to search
        self.verbose = verbose
        self.layer2 = layer2
        self.feature_mode = feature_mode

    def get_features_labels(
        self,
        layer2: Optional[bool] = None,
        feature_mode: Optional[FeatureMode] = None,
        max_pairs: Optional[int] = None,
        seed: Optional[int] = None,
    ) -> tuple[np.ndarray, list[int]]:
        if self.verbose:
            print("Extracting features and labels...")

        use_layer2 = self.layer2 if layer2 is None else layer2
        use_mode = self.feature_mode if feature_mode is None else feature_mode

        offsets, labels_arr = build_pair_dataset(
            self.adj,
            d=self.d,
            mode=use_mode,
            layer2=use_layer2,
            max_pairs=max_pairs,
            seed=seed,
        )
        features = sm.add_constant(offsets.reshape(-1, 1))
        labels = labels_arr.tolist()

        if self.verbose:
            print(f"Feature matrix shape: {features.shape}, edges={sum(labels)}")

        return features, labels

    def _fit_offset_logit(
        self,
        offsets: np.ndarray,
        labels: np.ndarray,
    ) -> Any:
        """Fit logit(y) = sigma + offsets with sigma as intercept."""
        y = np.asarray(labels, dtype=int)
        x = np.ones((len(y), 1), dtype=float)
        off = np.asarray(offsets, dtype=float)

        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", message="overflow encountered in exp")
            warnings.filterwarnings("ignore", message="divide by zero encountered in log")
            warnings.filterwarnings("ignore", category=RuntimeWarning, module="statsmodels")

            for method in ("bfgs", "newton", "lbfgs"):
                try:
                    model = sm.Logit(y, x, offset=off)
                    result = model.fit(method=method, disp=self.verbose, maxiter=300)
                    if np.isfinite(result.llf):
                        return result
                except Exception:
                    continue

            model = sm.Logit(y, x, offset=off)
            return model.fit_regularized(method="l1", alpha=1e-4, disp=self.verbose)

    def compute_aic(
        self,
        d_est: Optional[int] = None,
        feature_mode: Optional[FeatureMode] = None,
        layer2: Optional[bool] = None,
        extra_penalty: float = 0.0,
    ) -> dict[str, float]:
        """Paper AIC: -2*ll + 2 (one parameter sigma)."""
        d_use = self.d if d_est is None else d_est
        use_mode = self.feature_mode if feature_mode is None else feature_mode
        use_layer2 = self.layer2 if layer2 is None else layer2

        offsets, labels_arr = build_pair_dataset(
            self.adj,
            d=d_use,
            mode=use_mode,
            layer2=use_layer2,
        )
        from .offset_logit import aic_from_offset_fit, fit_offset_logit_fast

        sigma_hat, ll = fit_offset_logit_fast(offsets, labels_arr)
        fit = aic_from_offset_fit(sigma_hat, ll, extra_penalty=extra_penalty)
        return {
            "aic": fit["aic"],
            "ll": fit["ll"],
            "k": fit["k"],
            "sigma_hat": fit["sigma_hat"],
            "d_est": float(d_use),
            "n_obs": float(len(labels_arr)),
        }

    def select_d(
        self,
        d_candidates: Optional[list[int]] = None,
        feature_mode: Optional[FeatureMode] = None,
        extra_penalty_per_d: float = 0.0,
    ) -> tuple[int, dict[int, dict[str, float]]]:
        """Return argmin_d AIC(d) and per-d stats."""
        if d_candidates is None:
            d_candidates = [0, 1, 2, 3]
        use_mode = self.feature_mode if feature_mode is None else feature_mode
        stats: dict[int, dict[str, float]] = {}
        for d_c in d_candidates:
            stats[d_c] = self.compute_aic(
                d_est=d_c,
                feature_mode=use_mode,
                extra_penalty=extra_penalty_per_d * d_c,
            )
        best = min(stats, key=lambda d: stats[d]["aic"])
        return best, stats

    def estimate_parameters(
        self,
        l1_wt: float = 1,
        alpha: float = 0,
        features: Optional[np.ndarray] = None,
        labels: Optional[list[int]] = None,
        fix_beta: bool = True,
    ) -> tuple[Any, np.ndarray, np.ndarray]:
        """
        Fits the logistic regression model using the extracted features and labels.

        When ``fix_beta=True`` (default), the coefficient of the degree-sum
        predictor is fixed at 1 (used as an offset) and only the intercept
        sigma is estimated — matching the paper's formulation.  When
        ``fix_beta=False``, both sigma and beta are estimated freely
        (legacy behaviour).

        Args:
            l1_wt (float): The L1 weight (0 for pure L2, 1 for pure L1).
                Only used when ``fix_beta=False``.
            alpha (float): Regularization strength.
                Only used when ``fix_beta=False``.
            fix_beta (bool): If True, fix beta=1 and estimate only sigma
                via offset logistic regression (paper formulation).
        """
        if features is None or labels is None:
            features, labels = self.get_features_labels()

        if self.verbose:
            print("\nStarting parameter estimation...")
            print(f"fix_beta={fix_beta}")

        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", message="overflow encountered in exp")
            warnings.filterwarnings("ignore", message="divide by zero encountered in log")
            warnings.filterwarnings("ignore", category=RuntimeWarning, module="statsmodels")

            if fix_beta:
                intercept_col = features[:, 0:1]
                offset_col = features[:, 1]
                model = sm.Logit(labels, intercept_col, offset=offset_col)
                try:
                    result = model.fit(method='bfgs', disp=self.verbose)
                except (np.linalg.LinAlgError, Exception):
                    result = model.fit_regularized(
                        method='l1', alpha=1e-4, disp=self.verbose,
                    )
            else:
                model = sm.Logit(labels, features)
                if l1_wt in [0, 1]:
                    result = model.fit_regularized(
                        method='l1' if l1_wt == 1 else None,
                        alpha=alpha, disp=self.verbose,
                    )
                else:
                    result = model.fit_regularized(
                        method='elastic_net', alpha=alpha,
                        L1_wt=l1_wt, disp=self.verbose,
                    )

        params = result.params

        if self.verbose:
            param_vals = params.values if hasattr(params, 'values') else params
            print(f"Estimated parameters: {param_vals}")
            mle_ret = getattr(result, 'mle_retvals', None)
            if mle_ret:
                print(f"Converged: {mle_ret.get('converged', 'N/A')}")

        return result, params, features
