name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install minimal test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            numpy==1.26.4 \
            scipy==1.12.0 \
            networkx==3.2.1 \
            pandas==2.2.1 \
            statsmodels==0.14.1 \
            tqdm==4.66.4 \
            pytest==8.3.2

      - name: Run tests
        run: |
          pytest -q


